[package]
name = "forwarded"
version = "1.0.0"
authors = ["sohayl <sohayl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.4"
url = "2.2.2"
